# Jekyll Resume Theme

# Site settings
title: Hyun Ahn
email: hahn@kgu.ac.kr
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://gurami85.github.io"
name: Dr. Hyun Ahn
job: Research Professor at Kyonggi University
affiliation: Kyonggi University
location: Gyeonggi, South Korea
languages: Java, C, Python, JSP, and Javascript
twitter_username: mattcouchman
github_username:  gurami85
codepen_username:  mattcouchman
email_address: hahn@kgu.ac.kr
future: true
timezone: Asia/Seoul

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
